### ISSUE TITLE
[Feature] Proxy

### ISSUE THREAD

**Issue by Sergapr** [MC-Terminal/minecraft-terminal#11]
It is very cool future, it helps to bypass protection is server dont allow to use more than 5 account simultaneously for exaple

**Comment by Sergapr** [comment]
Thanks a lot, good job.
But what about private proxy with username and password?

**Comment by 678435021** [comment]
> Thanks a lot, good job. But what about private proxy with username and password?

Ohh yeah... I forgot about that

**Comment by 678435021** [comment]
> Thanks a lot, good job. But what about private proxy with username and password?

Done.
