### ISSUE TITLE
AutoFish bugs

### ISSUE THREAD

**Issue by Sergapr** [MC-Terminal/minecraft-terminal#14]
After 15 minutes after using autofish I found some bugs.
1. There are a lot of reasons for stop fishing and u can't resume a fishing because after stop it's work incorrect 
2. Bot will be near the water for fishing. If bot 
far from the hook, he can't catch the fish.
3. What about auto start function like in Minecraft console client? I am about starting fishing after some time after spawn.
4. What about Anti-cancelling function. I think if u start fishing, u want catch a fish. So, nvm why it stopped, it will resume fishing.

**Comment by 678435021** [comment]
> 1. There are a lot of reasons for stop fishing and u can't resume a fishing because after stop it's work incorrect

Can you send a video of what's happening

> 2. Bot will be near the water for fishing. If bot
>        far from the hook, he can't catch the fish.

You just have to position it correctly for it to work
