### ISSUE TITLE
Start it on Heroku

### ISSUE THREAD

**Issue by Sergapr** [MC-Terminal/minecraft-terminal#15]
It is possible to start a Mc-term on heroku or another free platform?
In future create a bridge among Mc-term and Discord, or Telegram. 
So, u can start it on Heroku and control using ur smartphone.

**Comment by 678435021** [comment]
For that you can just make your own plugin...

**Comment by Sergapr** [comment]
Okay, I will try, thank you

**Comment by 678435021** [comment]
> Okay, I will try, thank you

If you run into issues you can post about it here

**Comment by Sergapr** [comment]
Okay, thanks a lot
