### ISSUE TITLE
Smart Follow crash

### ISSUE THREAD

**Issue by SavageTheUnicorn** [MC-Terminal/minecraft-terminal#18]
**Describe the bug**
When running .smartfollow the bot will crash

**To Reproduce**
Start the bot and run .smartfollow <playername> <range>
Wait a second or two for the crash and error

**Expected behavior**
Bot follows the selected player at the range without fail using advanced pathfinding

**Setup:**
 - Ubuntu 20.04
 - Latest Version
 - Node 16.18.0

**Additional context**
[ERR] An unexpected error occurred.
      Cannot read properties of undefined (reading 'goto')
          at commands.smartFollow (/usr/local/lib/node_modules/mc-term/lib/commands.js:682:26)
          at async Object.commands.optcmd (/usr/local/lib/node_modules/mc-term/lib/commands.js:1120:2)

**Comment by SavageTheUnicorn** [comment]
Same with .pathfind <x y z>

**Comment by SavageTheUnicorn** [comment]
.inventory 0 dropall produces this error; [ERR] An unexpected error occurred.
      window is not defined
          at commands.inventory (/usr/local/lib/node_modules/mc-term/lib/commands.js:912:3)
          at Object.commands.optcmd (/usr/local/lib/node_modules/mc-term/lib/commands.js:1120:8)

**Comment by SavageTheUnicorn** [comment]
Running npm up -g mc-term doesn't work for me even though I installed via npm. Everytime I run the bot it says the update patch is available still though. Just says "up to date" when i try to update.

**Comment by SavageTheUnicorn** [comment]
npm uninstall mc-term did nothing aswell (even adding the -g flag)

**Comment by SavageTheUnicorn** [comment]
.smartfollow has been fixed, amazing work. .inventory 0 dropall new error; >.inventory 0 dropall
[INFO] Dropping all items in window #0
>Item {
  type: 952,
  count: 4,
  metadata: 0,
  nbt: null,
  name: 'golden_carrot',
  displayName: 'Golden Carrot',
  stackSize: 64,
  slot: 36
}
[ERR] An unexpected error occurred.
      it's not night and it's not a thunderstorm
          at EventEmitter.sleep (/root/.nvm/versions/node/v16.18.0/lib/node_modules/mc-term/node_modules/mineflayer/lib/plugins/bed.js:82:13)
          at commands.inventory (/root/.nvm/versions/node/v16.18.0/lib/node_modules/mc-term/lib/commands.js:930:14)

**Comment by 678435021** [comment]
> Running npm up -g mc-term doesn't work for me even though I installed via npm. Everytime I run the bot it says the update patch is available still though. Just says "up to date" when i try to update.

can you run `mc-term -v`, `which mc-term`, `npm list`, `npm list -g` and send me their outputs

**Comment by 678435021** [comment]
> Adding !# to a command ingame does not send it to the terminal via rcon either. Is there something I'm missing regarding rcon? If I can't send commands to the bot ingame without ssh into the terminal it kind of defeats the purpose for me.

It got removed sometime ago. I'll try adding it again

**Comment by SavageTheUnicorn** [comment]
> > Running npm up -g mc-term doesn't work for me even though I installed via npm. Everytime I run the bot it says the update patch is available still though. Just says "up to date" when i try to update.
> 
> can you run `mc-term -v`, `which mc-term`, `npm list`, `npm list -g` and send me their outputs

This issue was fixed, I had ran sudo su while I was already root and it caused issues until I exited to normal user and redid sudo su. Would you still like me to do this? I'd really appreciate if you did add rcon back! The only other feature that would really be a cool add on would be a guard/pve command. Such as if you say .guard <playername or xyz coords> <radius> the bot would follow the player/path to the coords and attack any mobs that come within said radius.

**Comment by SavageTheUnicorn** [comment]
> .smartfollow has been fixed, amazing work. .inventory 0 dropall new error; >.inventory 0 dropall [INFO] Dropping all items in window #0
> 
> > Item {
> > type: 952,
> > count: 4,
> > metadata: 0,
> > nbt: null,
> > name: 'golden_carrot',
> > displayName: 'Golden Carrot',
> > stackSize: 64,
> > slot: 36
> > }
> > [ERR] An unexpected error occurred.
> > it's not night and it's not a thunderstorm
> > at EventEmitter.sleep (/root/.nvm/versions/node/v16.18.0/lib/node_modules/mc-term/node_modules/mineflayer/lib/plugins/bed.js:82:13)
> > at commands.inventory (/root/.nvm/versions/node/v16.18.0/lib/node_modules/mc-term/lib/commands.js:930:14)

This issue still persists though, will send outputs.

**Comment by 678435021** [comment]
The inventory should be fixed now.

**Comment by 678435021** [comment]
You can now enable rcon in the config (it's disabled by default)

![image](https://user-images.githubusercontent.com/110736028/200820280-7eced611-5e88-499a-a3b1-1b73a5ed33b6.png)
