### ISSUE TITLE
Connect to server on custom PORT

### ISSUE THREAD

**Issue by SavageTheUnicorn** [MC-Terminal/minecraft-terminal#19]
**Is your feature request related to a problem? Please describe.**
When trying to connect the bot to a server that is not on the default port 25565, the bot cannot connect.

**Describe the solution you'd like**
The ability to change the port in the credentials.toml file

**Describe alternatives you've considered**
I would change my server back to port 25565, but it is in use by another service.

**Additional context**
If this is already possible, please let me know how it is achieved and close this issue as completed if I don't myself. Thanks!

**Comment by 678435021** [comment]
You can change the port
```toml
server = "localhost:12345" #IP:PORT
```

**Comment by SavageTheUnicorn** [comment]
Then I am having an issue with the bot. I tried that already and it still said "could not connect". Will check for more info.

**Comment by SavageTheUnicorn** [comment]
Yea, I cannot connect to the server despite copy and pasting the exact IP+PORT from my server panel. The only error that displays is getaddrinfo ENOTFOUND "ip:port"

**Comment by SavageTheUnicorn** [comment]
In fact, the server in question has been online for the last 7days 7hours and 53 minutes. Before changing the port of the server, this was not an issue. All required ports are opened and forwarded as well as all DNS settings being proper.

**Comment by 678435021** [comment]
It does work for me though

https://user-images.githubusercontent.com/110736028/202253357-117bebed-64d0-4e95-ba5b-6ee11b0372bb.mp4

**Comment by 678435021** [comment]
can you make sure it's not a problem with your server

**Comment by SavageTheUnicorn** [comment]
> can you make sure it's not a problem with your server

Confirmed not an issue with the server, can connect just fine on vanilla, forge, and fabric clients with the same ip and port.

**Comment by 678435021** [comment]
> I can share the ip and port for you to test personally if you would like.

yeah sure

**Comment by 678435021** [comment]
> Seeing the video, did the Auth type change from cracked to "!"?

"!" uses the default option which is cracked

**Comment by SavageTheUnicorn** [comment]
> > I can share the ip and port for you to test personally if you would like.
> 
> yeah sure

The ip and port is 129.146.43.220:25566

**Comment by SavageTheUnicorn** [comment]
This was not an issue before rcon was added back. I hadn't tried updating mc-term until today merging that update.

**Comment by 678435021** [comment]
It should be fixed now. Update to the latest version

**Comment by 678435021** [comment]
> The only thing that'd make the bot perfect for rcon usage is if the bot also had an attack command for mobs only instead of just players heh

I just added that with the newest update.

Attack all pigs in a 3 block radius.
```
.attack name = pig 10 3 1
```

Attack everything that isn't a pig in a 3 block radius.

```
.attack name != pig 10 3 1
```

**Comment by SavageTheUnicorn** [comment]
> > The only thing that'd make the bot perfect for rcon usage is if the bot also had an attack command for mobs only instead of just players heh
> 
> I just added that with the newest update.
> 
> Attack all pigs in a 3 block radius:
> ```
> .attack name = pig 10 3 1
> ```
> 
> Attack everything that isn't a pig in a 3 block radius:
> ```
> .attack name != pig 10 3 1
> ```
> 
> Attack a player named notch:
> ```
> .attack username = notch 10 3 1
> ```

Very interesting! Does this work in tandem with the follow/smartfollow command? If so it's flawless.

**Comment by 678435021** [comment]
> Very interesting! Does this work in tandem with the follow/smartfollow command? If so it's flawless.

It does work

> Is there documentation with the names of the mobs supported?

See [prismarine-entity API](https://github.com/PrismarineJS/prismarine-entity#api) and [attack command](https://github.com/MC-Terminal/minecraft-terminal#attack)

**Comment by 678435021** [comment]
> Attack all pigs in a 3 block radius:
> ```
> .attack name = pig 10 3 1
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Attack everything that isn't a pig in a 3 block radius:
> ```
> .attack name != pig 10 3 1
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Attack a player named notch:
> ```
> .attack username = notch 10 3 1
> ```

I just changed the syntax. see [attack command](https://github.com/MC-Terminal/minecraft-terminal#attack)

**Comment by 678435021** [comment]
> Very interesting! Does this work in tandem with the follow/smartfollow command? If so it's flawless.

Use smart follow instead of follow as it might be buggy. Also try using a slow cps 8 and lower should be fine

https://user-images.githubusercontent.com/110736028/202532855-ec2583a5-af05-4c7a-8707-2dc261a0cc15.mp4

**Comment by SavageTheUnicorn** [comment]
Would using kind=Hostile mobs instead of kind=Passive mobs achieve the expected result? That demonstration was very informative as well, thank you.

**Comment by 678435021** [comment]
>I can't figure out the syntax thinking I tried .attack name≠SavageTheUnicorn 6 5 1 but the bot still attacks the player with that name.

`name` means the entity's name e.g. player, pig, cow. If you want a player's username you should use `username`:
```
>.attack 'name=player,username!=SavageTheUnicorn' 6 5 1
```

`name=player`, `username!=SavageTheUnicorn` these two conditions must be matched for it to attack the nearest entity if they're not, it'll look for another entity in it's range. So it'll attack all players except `SavageTheUnicorn`

**Comment by SavageTheUnicorn** [comment]
Yea I'm stumped. I can't seem to get the bot to attack all entities while ignoring a specific player. Even using your example the bot only attacks other players, not mobs. Would you mind lending some help?

**Comment by 678435021** [comment]
Yeah I added some stuff to it and changed the syntax.

Update to the latest version and try

```
.attack name=player&username!=SavageTheUnicorn 6 3 0.4
```
