### ISSUE TITLE
Unexpected error when trying to type in chat

### ISSUE THREAD

**Issue by Dominik159E0** [MC-Terminal/minecraft-terminal#39]
### Operating System

Windows, Linux

### Version of Minecraft Terminal

5.9.0

### Version of Node

19.3.0

### Description of bug

Crash
![obrázok](https://user-images.githubusercontent.com/90928810/209351080-6b79ab58-96bf-4658-a114-f9f006a6c03a.png)

### Steps to reproduce

Join a server
type something 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by 678435021** [comment]
restart it with the --debug flag send me the output

**Comment by 678435021** [comment]
This is a bug with [node-minecraft-protocol](https://github.com/PrismarineJS/node-minecraft-protocol) with 1.19 and the new chat signing

You just have to wait for the bug to get fixed upstream

**Comment by 678435021** [comment]
Fixed
