### ISSUE TITLE
Mineflayer item downloader

### ISSUE THREAD

**Issue by Sergapr** [MC-Terminal/minecraft-terminal#8]
Hi! I am looked at add Mineflayer item downloader to minecraft-terminal, but i cant do it.
I am follow instructions, but it dont download a map..
Help pls

**Comment by Sergapr** [comment]
@678435021 Hi bro, can u help me?

**Comment by 678435021** [comment]
You can add it by making your own [plugin](https://github.com/MC-Terminal/minecraft-terminal#plugins)

**Comment by 678435021** [comment]
I can make it for you tho

**Comment by Sergapr** [comment]
I am really noob, can u send an example with added plugin? 
I just want to add an Captha bypass by addind Item-map-downloading
and AutoFish

**Comment by 678435021** [comment]
Yeah sure I'll do that

**Comment by Sergapr** [comment]
Oh, I'm very grateful

**Comment by 678435021** [comment]
@Sergapr Finished! Let me know if it works

Download: [mapdown.zip](https://github.com/MC-Terminal/minecraft-terminal/files/9692876/mapdown.zip)

**Comment by Sergapr** [comment]
Now I will put downloader directoroty into plugins.json
And will I type anything into cmd?

**Comment by 678435021** [comment]
You should first extract the zip and open cmd and run `npm install` then put the downloader.js file path into plugins.json

**Comment by 678435021** [comment]
BTW [mineflayer-item-map-downloader](https://github.com/IceTank/mineflayer-item-map-downloader) only downloads maps inside of item frames not held maps

**Comment by Sergapr** [comment]
I am sorry bro, i am knew im noob, but right now i am working on  loading plugins and want to test a testplugin.js
![image](https://user-images.githubusercontent.com/106835861/193464255-9b958e5a-8801-4790-8109-b08e81291058.png)
I put the testplugin.js path into plugins.json at folder "config"
![image](https://user-images.githubusercontent.com/106835861/193464388-3abc393d-430e-4487-934a-732abfa0f84a.png)
And when i start mc term and type .test i have an error 

![image](https://user-images.githubusercontent.com/106835861/193464423-4abad099-d8f6-448b-b86f-c01740b08a1c.png)

**Comment by 678435021** [comment]
Can you show me the contents of testplugin.js

**Comment by Sergapr** [comment]
![image](https://user-images.githubusercontent.com/106835861/193464503-326b3012-6352-4763-a7a6-992ad3fd7724.png)

**Comment by 678435021** [comment]
oh you might be editing the wrong plugins.json

can you run `mc-term -gcp` and then go to that directory and edit the plugins.json that's inside it

**Comment by 678435021** [comment]
That _should_ work

**Comment by Sergapr** [comment]
![image](https://user-images.githubusercontent.com/106835861/193464704-6a19c2c1-6a4a-420f-9740-6446aea91738.png)

![image](https://user-images.githubusercontent.com/106835861/193464720-5e9c0e85-21f3-4648-9024-a5587ebf9766.png)

![image](https://user-images.githubusercontent.com/106835861/193464725-e49b87fe-6660-411b-b56b-43fb9fe4303b.png)

![image](https://user-images.githubusercontent.com/106835861/193464733-8912c830-e4dd-4422-8be9-3e298d6b8dcd.png)

**Comment by Sergapr** [comment]
Sorry, i am taking a lot of ur time, i knew it is my problem

**Comment by 678435021** [comment]
It's ok

**Comment by 678435021** [comment]
Try changing it by running `mc-term -scp /path/to/config`

then edit it again

**Comment by Sergapr** [comment]
will i replace  /path/to/config to my directory?

**Comment by Sergapr** [comment]
Can u connect to my pc with AnyDesk pls? if u have a time

**Comment by 678435021** [comment]
no no "/path/to/config" is anywhere you like it could be C:\users\wherever

**Comment by 678435021** [comment]
> Can u connect to my pc with AnyDesk pls? if u have a time

Okay I'll try doing that

**Comment by Sergapr** [comment]
342325812 is my desktop id in AnyDesk

**Comment by 678435021** [comment]
okay
Ill try connecting

**Comment by 678435021** [comment]
I am now installing anydesk give me like 2 minutes

**Comment by Sergapr** [comment]
Yeah sure

**Comment by 678435021** [comment]
Okay I am connected

**Comment by 678435021** [comment]
Should be fixed now!!

**Comment by 678435021** [comment]
> ![image](https://user-images.githubusercontent.com/106835861/193464725-e49b87fe-6660-411b-b56b-43fb9fe4303b.png)

You should replace '\' with '/'

**Comment by 678435021** [comment]
Can you confirm that everything is working please

**Comment by Sergapr** [comment]
> Can you confirm that everything is working please

everything is working 👍👌
Thanks again bro)

**Comment by 678435021** [comment]
You can now enable the builtin plugin to download maps

![image](https://user-images.githubusercontent.com/110736028/194317693-57242ebc-05b6-4d55-b8af-b659f057e063.png)
