### ISSUE TITLE
Timer problem

### ISSUE THREAD

**Issue by Sergapr** [MC-Terminal/minecraft-terminal#9]
I have a problem with server.
If I Use Minecraft console client, I have been kicked with reason BadPackets when join mini game (https://github.com/MCCTeam/Minecraft-Console-Client/issues/2257)
If I use Mc-trem, server kick a bot with reason Timer.
In https://github.com/MCCTeam/Minecraft-Console-Client/issues/2257 issue I am already wrote how to reproduce a bug, can u help fix it?

**Comment by 678435021** [comment]
What minecraft version were you using?

**Comment by Sergapr** [comment]
> What minecraft version were you using?

1.16.5

**Comment by Sergapr** [comment]
I am sorry, I am going to sleep and can't answer your questions till tomorrow

**Comment by 678435021** [comment]
@Sergapr wait are you still here?

**Comment by 678435021** [comment]
Huh that might be a problem in the configuration

**Comment by 678435021** [comment]
Update to the latest version and make sure 'tickTimeout' is set to **40**

![timer](https://user-images.githubusercontent.com/110736028/194775966-9ea476d2-f122-4280-95e1-1c82e7508ebe.png)

**Comment by 678435021** [comment]
That seems to fix it as I have been online in a minigame for 5 minutes without being kicked

**Comment by Sergapr** [comment]
Thank u very much! I will test it tomorrow

**Comment by Sergapr** [comment]
> That seems to fix it as I have been online in a minigame for 5 minutes without being kicked

How to update mc-term?

**Comment by 678435021** [comment]
> > That seems to fix it as I have been online in a minigame for 5 minutes without being kicked
> 
> How to update mc-term?

If you installed it with npm just run `npm up -g`

**Comment by Sergapr** [comment]
Where is a config file?

**Comment by 678435021** [comment]
> Where is a config file?

Run `mc-term -gcp`

**Comment by Sergapr** [comment]
![image](https://user-images.githubusercontent.com/106835861/194848321-02aff6a2-0c2d-4994-a26d-11674fa270f1.png)
   tickTimeout = 40 but server kicks me

**Comment by Sergapr** [comment]
342325812 anydesk id
connect if u can pls

**Comment by 678435021** [comment]
okay lol

**Comment by 678435021** [comment]
> 342325812 anydesk id connect if u can pls

![image](https://user-images.githubusercontent.com/110736028/194848676-406d03f3-073c-4a46-8ede-fa11ac992ef4.png)

**Comment by Sergapr** [comment]
Thanks again

**Comment by Sergapr** [comment]
@678435021 do u have a discord or telegram? Or i should open issues?

**Comment by 678435021** [comment]
Yeah you can just open issues it's fine

**Comment by Sergapr** [comment]
Ok, i just have some ideas for builtin plugins and futures
